[project]
name = "screener-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.26",
    "aiohttp>=3.13.3",
    "aiohttp-socks>=0.10",
    "python-socks[asyncio]>=2.6",
    "aiosqlite~=0.20.0",
    "alembic~=1.13.1",
    "binance-sdk-derivatives-trading-usds-futures>=9.0.0",
    "cachetools~=5.3.3",
    "fluent-runtime==0.4.0",
    "loguru>=0.7.3",
    "pydantic>=2.12",
    "pydantic-settings~=2.2.1",
    "python-dotenv>=1.2.1",
    "sqlalchemy~=2.0.30",
]


[tool.ruff]
target-version = "py312"
