"""upd user

Revision ID: 117418b29850
Revises: 1470a8c67cda
Create Date: 2026-03-19 20:31:13.638272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117418b29850'
down_revision: Union[str, None] = '1470a8c67cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('alert_20m', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'alert_20m')
    # ### end Alembic commands ###
